### ISSUE TITLE
Self-contained Dockerfiles

### ISSUE THREAD

**Issue by pierDipi** [christophd/kn-connectors#3]
One piece that will help producing the final artifacts is to remove the need to have a local packaging (off container build) with multi stage builds:

https://github.com/christophd/kn-connectors/blob/a919efe7b528594b6126f24d48a993e9c3d81432/timer-source/src/main/docker/Dockerfile.jvm#L21-L27

**Comment by matzew** [comment]
/close

moved to actual repo: knative-extensions/eventing-integrations
